import Head from 'next/head'
import { Inter } from 'next/font/google'
import HomePage from './Home/index'
import Footer from '../../components/Footer/Footer'
import TopBar from '../../components/Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>আমরা গ্রামবাসী কল্যাণ সমিতি</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='mx-auto max-w-screen-2xl px-2'>
        <TopBar />
        <HomePage />
        <Footer />
      </main>
    </>
  )
}
